### ISSUE TITLE
WISH: Run checks with a random port rather than a fixed (port 36761)

### ISSUE THREAD

**Issue by HenrikBengtsson** [luomus/finbif#16]
Hello.  This is not an end-user feature request, but rather a wish from someone who tests **finbif** as a reverse dependency package.

When I'm running revdep checks on **future** (using the **revdepcheck** package), each package tested is processed with the CRAN version of **future** and the development version of **future**.  These two checks are run at the same time.

Now, since one of the **finbif** package tests opens a server on port 36761;

https://github.com/luomus/finbif/blob/4ef80271a32ad420aeaee692813ef0e229775f28/tests/testthat/test-local-finbif_occurrence_load.R#L24

the above two checks will compete for this port, and one will fail, e.g.

```
══ Failed tests ════════════════════════════════════════════════════════════════
  70   │   ── Error ('test-local-finbif_occurrence_load.R:26'): (code run outside of `test_that()`) ──
  71   │   <callr_status_error/callr_error/rlib_error_3_0/rlib_error/error/condition>
  72   │   Error: ! failed to start webfakes app process: in callr subprocess.
  73   │   Caused by error: 
  74   │   ! Cannot start webfakes web server @rweb.c:479 (server_start)
  75   │   Error log:
  76   │   [1670565560] [error] [client ] cannot bind to 127.0.0.1:36761: 98 (Address already in use)
  77   │   [1670565560] [error] [client ] Failed to setup server ports
  78   │   
  79   │   Backtrace:
  80   │       ▆
  81   │    1. ├─base::options(finbif_dl_url = api[["url"]]()) at test-local-finbif_occurrence_load.R:26:2
  82   │    2. └─api[["url"]]()
  83   │    3.   └─self$start()
```

# Ask

Is it important that it's port 36761 here?  If not, would you consider using a random port instead, e.g.

```r
port <- sample(1024:65535, size = 1L)
api <- local_app_process(app, .local_envir = teardown_env(), port = port)
```

Would that work for you?   That would lower the risk of port clashes.

BTW, if you're willing to introduce more dependencies, one can even make sure that the random port is free by using either:

```r
port <- parallelly::freePort()
```

or

```r
port <- port4me::port4me()
```

**Comment by wkmor1** [comment]
Fixed in [dev](https://github.com/luomus/finbif/commit/93a7e770202f04fe1d46d7c290bb65f613ad880d). Will send to CRAN as soon as I can.

**Comment by HenrikBengtsson** [comment]
Wow, that was a much easier fix than what I proposed.

> Will send to CRAN as soon as I can.

Thx. No rush need on my end.

**Comment by wkmor1** [comment]
Yeah, a few test artifacts were sensitive to the source URLs. My original quick fix at the time was to set the port so URLs were stable. But just making the tests insensitive to the port component was not really too hard. In hindsight it was probably always a bad idea on my part to take port selection away from the OS. Lesson learned :)

**Comment by wkmor1** [comment]
This should be fixed on CRAN version now too

**Comment by HenrikBengtsson** [comment]
Thank you
